#obj-y	:= intelli_plug.o bricked_hotplug.o msm_zen_decision.o
#obj-$(CONFIG_ASMP) 		+= autosmp.o
#obj-$(CONFIG_FAST_HOTPLUG) 	+= fast_hotplug.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_CLUSTER_PLUG)	+= cluster_plug.o
